server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: nt-ms1
          uri: http://localhost:9091/
          predicates:
            - Path=/ms1/**
          filters:
            - name: PreFilter
            - name: PostFilter
        - id: nt-ms2
          uri: http://localhost:9092/
          predicates:
            - Path=/ms2/**