server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
---
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/ms1/**
          filters:
            - PreFilter1
            - PreFilter2
            - SinkFilter
        - id: ms2
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/ms2/**
          filters:
            - PreFilter1
            - PreFilter2
            - PostFilter
        - id: test
          uri: localhost:9090
          predicates:
            - Path=/test/**
          filters:
            - name: TestConfigPropertiesFilter
              args:
                reCaptaEnable: true
---
aws:
  accessKey: AKIATJQ37Q2WRFTNG6US
  secretKey: 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