server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: http://localhost:9091/
          predicates:
            - Path=/ms1/**
          filters:
            - name: PreFilterV2
            #- name: PostFilter
        - id: ms2
          uri: http://localhost:9092/
          predicates:
            - Path=/ms2/**
          filters:
            - name: PreFilter
            - name: PostFilter
---
aws:
  accessKey: AKIATJQ37Q2WRFTNG6US
  secretKey: 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