server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
---
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/ms1/**
          filters:
            - name: Filter_1
            - name: Filter_2
        - id: ms1-feign-test
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/feign/**
        - id: ms2
          uri: http://localhost:9092/
          predicates:
            - Path=/ms2/**
          filters:
            - name: Filter_1
            - name: Filter_2
---
aws:
  accessKey: AKIATJQ37Q2WRFTNG6US
  secretKey: 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